-- MySQL Script generated by MySQL Workbench
-- Wed Nov 26 12:14:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA` (
  `pers_documento` BIGINT(10) NOT NULL,
  `pers_nombres` VARCHAR(45) NOT NULL,
  `pers_apellidos` VARCHAR(45) NOT NULL,
  `pers_direccion` VARCHAR(45) NOT NULL,
  `pers_telefono` BIGINT(11) NOT NULL,
  `pers_tipodoc` VARCHAR(5) NOT NULL,
  `pers_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pers_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MARCA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MARCA` (
  `marc_id` INT NOT NULL,
  `marc_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`marc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ELEMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ELEMENTO` (
  `elem_placa` BIGINT(11) NOT NULL,
  `elem_descripcion` VARCHAR(45) NOT NULL,
  `elem_modelo` VARCHAR(45) NOT NULL,
  `MARCA_marc_id` INT NOT NULL,
  `elem_serial` VARCHAR(45) NOT NULL,
  `elem_fecha_compra` DATETIME NULL,
  `elem_vida_util` INT NULL,
  `elem_costo` BIGINT(12) NULL,
  PRIMARY KEY (`elem_placa`),
  INDEX `fk_ELEMENTO_MARCA_idx` (`MARCA_marc_id` ASC) VISIBLE,
  CONSTRAINT `fk_ELEMENTO_MARCA`
    FOREIGN KEY (`MARCA_marc_id`)
    REFERENCES `mydb`.`MARCA` (`marc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SEDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SEDE` (
  `sede_id` INT NOT NULL,
  `sede_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`sede_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SOLICITUD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SOLICITUD` (
  `solic_id` INT NOT NULL AUTO_INCREMENT,
  `solic_fecha_ini` DATETIME NOT NULL,
  `solic_fecha_fin` DATETIME NULL,
  `PERSONA_pers_documento` BIGINT(10) NOT NULL,
  `solic_destino` VARCHAR(45) NOT NULL,
  `solic_motivo` VARCHAR(45) NOT NULL,
  `solic_estado` VARCHAR(45) NOT NULL,
  `solic_observaciones` VARCHAR(45) NOT NULL,
  `SEDE_sede_id` INT NOT NULL,
  PRIMARY KEY (`solic_id`),
  INDEX `fk_SOLICITUD_PERSONA1_idx` (`PERSONA_pers_documento` ASC) VISIBLE,
  INDEX `fk_SOLICITUD_SEDE1_idx` (`SEDE_sede_id` ASC) VISIBLE,
  CONSTRAINT `fk_SOLICITUD_PERSONA1`
    FOREIGN KEY (`PERSONA_pers_documento`)
    REFERENCES `mydb`.`PERSONA` (`pers_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLICITUD_SEDE1`
    FOREIGN KEY (`SEDE_sede_id`)
    REFERENCES `mydb`.`SEDE` (`sede_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AMBIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AMBIENTE` (
  `amb_id` INT NOT NULL,
  `amb_nombre` VARCHAR(45) NULL,
  `SEDE_sede_id` INT NOT NULL,
  PRIMARY KEY (`amb_id`),
  INDEX `fk_AMBIENTE_SEDE1_idx` (`SEDE_sede_id` ASC) VISIBLE,
  CONSTRAINT `fk_AMBIENTE_SEDE1`
    FOREIGN KEY (`SEDE_sede_id`)
    REFERENCES `mydb`.`SEDE` (`sede_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ASIGNACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASIGNACION` (
  `ELEMENTO_elem_placa` BIGINT(11) NOT NULL,
  `AMBIENTE_amb_id` INT NOT NULL,
  `PERSONA_pers_documento` BIGINT(10) NOT NULL,
  `asig_id` INT NOT NULL AUTO_INCREMENT,
  `asig_fecha_ini` DATETIME NOT NULL,
  PRIMARY KEY (`asig_id`),
  INDEX `fk_ASIGNACION_AMBIENTE1_idx` (`AMBIENTE_amb_id` ASC) VISIBLE,
  INDEX `fk_ASIGNACION_PERSONA1_idx` (`PERSONA_pers_documento` ASC) VISIBLE,
  CONSTRAINT `fk_ASIGNACION_ELEMENTO1`
    FOREIGN KEY (`ELEMENTO_elem_placa`)
    REFERENCES `mydb`.`ELEMENTO` (`elem_placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASIGNACION_AMBIENTE1`
    FOREIGN KEY (`AMBIENTE_amb_id`)
    REFERENCES `mydb`.`AMBIENTE` (`amb_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASIGNACION_PERSONA1`
    FOREIGN KEY (`PERSONA_pers_documento`)
    REFERENCES `mydb`.`PERSONA` (`pers_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROL` (
  `rol_id` INT NOT NULL,
  `rol_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROL_PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROL_PERSONA` (
  `ROL_rol_id` INT NOT NULL,
  `PERSONA_pers_documento` BIGINT(10) NOT NULL,
  `SEDE_sede_id` INT NOT NULL,
  PRIMARY KEY (`ROL_rol_id`, `PERSONA_pers_documento`),
  INDEX `fk_ROL_PERSONA_PERSONA1_idx` (`PERSONA_pers_documento` ASC) VISIBLE,
  INDEX `fk_ROL_PERSONA_SEDE1_idx` (`SEDE_sede_id` ASC) VISIBLE,
  CONSTRAINT `fk_ROL_PERSONA_ROL1`
    FOREIGN KEY (`ROL_rol_id`)
    REFERENCES `mydb`.`ROL` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROL_PERSONA_PERSONA1`
    FOREIGN KEY (`PERSONA_pers_documento`)
    REFERENCES `mydb`.`PERSONA` (`pers_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROL_PERSONA_SEDE1`
    FOREIGN KEY (`SEDE_sede_id`)
    REFERENCES `mydb`.`SEDE` (`sede_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_SOLICITUD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_SOLICITUD` (
  `detsolic_id` INT NOT NULL AUTO_INCREMENT,
  `SOLICITUD_solic_id` INT NOT NULL,
  `ASIGNACION_asig_id` INT NOT NULL,
  PRIMARY KEY (`detsolic_id`, `SOLICITUD_solic_id`),
  INDEX `fk_DETALLE_SOLICITUD_SOLICITUD1_idx` (`SOLICITUD_solic_id` ASC) VISIBLE,
  INDEX `fk_DETALLE_SOLICITUD_ASIGNACION1_idx` (`ASIGNACION_asig_id` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE_SOLICITUD_SOLICITUD1`
    FOREIGN KEY (`SOLICITUD_solic_id`)
    REFERENCES `mydb`.`SOLICITUD` (`solic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_SOLICITUD_ASIGNACION1`
    FOREIGN KEY (`ASIGNACION_asig_id`)
    REFERENCES `mydb`.`ASIGNACION` (`asig_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTADOxELEMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTADOxELEMENTO` (
  `ELEMENTO_elem_placa` BIGINT(11) NOT NULL,
  `est_elem_id` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `est_fecha_registro` DATETIME NULL,
  INDEX `fk_ESTADOxELEMENTO_ELEMENTO1_idx` (`ELEMENTO_elem_placa` ASC) VISIBLE,
  PRIMARY KEY (`est_elem_id`),
  CONSTRAINT `fk_ESTADOxELEMENTO_ELEMENTO1`
    FOREIGN KEY (`ELEMENTO_elem_placa`)
    REFERENCES `mydb`.`ELEMENTO` (`elem_placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FIRMA_SOLICITUD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FIRMA_SOLICITUD` (
  `SOLICITUD_solic_id` INT NOT NULL,
  `firm_id` VARCHAR(45) NULL,
  `ROL_PERSONA_ROL_rol_id` INT NOT NULL,
  `ROL_PERSONA_PERSONA_pers_documento` BIGINT(10) NOT NULL,
  `firm_firmado` TINYINT NOT NULL,
  `firm_observacion` VARCHAR(45) NOT NULL,
  `firm_fecha_firmado` DATETIME NULL,
  INDEX `fk_FIRMA_SOLICITUD_SOLICITUD1_idx` (`SOLICITUD_solic_id` ASC) VISIBLE,
  INDEX `fk_FIRMA_SOLICITUD_ROL_PERSONA1_idx` (`ROL_PERSONA_ROL_rol_id` ASC, `ROL_PERSONA_PERSONA_pers_documento` ASC) VISIBLE,
  CONSTRAINT `fk_FIRMA_SOLICITUD_SOLICITUD1`
    FOREIGN KEY (`SOLICITUD_solic_id`)
    REFERENCES `mydb`.`SOLICITUD` (`solic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FIRMA_SOLICITUD_ROL_PERSONA1`
    FOREIGN KEY (`ROL_PERSONA_ROL_rol_id` , `ROL_PERSONA_PERSONA_pers_documento`)
    REFERENCES `mydb`.`ROL_PERSONA` (`ROL_rol_id` , `PERSONA_pers_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
